In [45]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [59]:
def model_train(X_train,X_test,y_train,y_test):
    N_estimators=[5,10,15]
    Criterion=['gini','entropy','log_loss']
    Max_depth=[3,6,None]
    min_samples_split=[2,4,6]
    min_samples_leaf=[2,4,6]
    Max_features=['sqrt', 'log2', None]
    accuracy=[]
    for i in range(3):
        a=RandomForestClassifier(n_estimators=N_estimators[i], criterion=Criterion[i], max_depth=Max_depth[i], min_samples_split=min_samples_split[i], min_samples_leaf=min_samples_leaf[i],  max_features=Max_features[i])
        acu=cross_val_score(a,X_train,y_train,cv=5)
        accuracy.append(sum(acu)/5)
    name=['N_estimators','Criterion','Max_depth','min_samples_split','min_samples_leaf','Max_features','accuracy']
    return accuracy

In [53]:
def print_result(accu):
   table=[['N_estimators',5,10,15],['Criterion','gini','entropy','log_loss'],['Max_depth',3,6,None],['min_samples_split',2,4,6],
       ['min_samples_leaf',2,4,6],['Max_features','sqrt', 'log2', None],['accuracy',accu[0],accu[1],accu[2]]
      ]
   res=pd.DataFrame(table,columns=['Parameter','CATEGORY 1','CATEGORY 2','CATEGORY 3'])
   maxi=0
   for i in range(len(accu)):
       if maxi<accu[i]:
           maxi=accu[i]
           n=i+1
   print(f"Category {n} have high accuracy",maxi)
           
   return res

In [54]:
from sklearn.model_selection import train_test_split
df1=pd.read_csv("Dry_Bean_Dataset.csv")
dic={'Class':{'SEKER':1, 'BARBUNYA':2, 'BOMBAY':3, 'CALI':4, 'HOROZ':5, 'SIRA':6, 'DERMASON':7}}
df1=df1.replace(dic)
X=df1.drop('Class',axis=1)
y=df1.Class
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,shuffle=True)
res=model_train(X_train,X_test,y_train,y_test)
print_result(res)

Category 3 have high accuracy 0.9286089238845144

           Parameter CATEGORY 1 CATEGORY 2 CATEGORY 3
0       N_estimators          5         10         15
1          Criterion       gini    entropy   log_loss
2          Max_depth          3          6       None
3  min_samples_split          2          4          6
4   min_samples_leaf          2          4          6
5       Max_features       sqrt       log2       None
6           accuracy   0.835696   0.912336   0.928609

In [55]:
df2=pd.read_csv("ricin.csv")
df2.Class.unique()
dic2={'Class':{'Kecimen':1, 'Besni':2}}
df2=df2.replace(dic2)
X=df2.drop('Class',axis=1)
y=df2.Class
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,shuffle=True)
res=model_train(X_train,X_test,y_train,y_test)
print_result(res)

Category 3 have high accuracy 0.8968253968253969

           Parameter CATEGORY 1 CATEGORY 2 CATEGORY 3
0       N_estimators          5         10         15
1          Criterion       gini    entropy   log_loss
2          Max_depth          3          6       None
3  min_samples_split          2          4          6
4   min_samples_leaf          2          4          6
5       Max_features       sqrt       log2       None
6           accuracy   0.888889   0.873016   0.896825

In [57]:
df3=pd.read_csv("winequality-red.csv")
X=df3.drop('quality',axis=1)
y=df3.quality
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,shuffle=True)
res=model_train(X_train,X_test,y_train,y_test)
print_result(res)

Category 1 have high accuracy 0.65625

           Parameter CATEGORY 1 CATEGORY 2 CATEGORY 3
0       N_estimators          5         10         15
1          Criterion       gini    entropy   log_loss
2          Max_depth          3          6       None
3  min_samples_split          2          4          6
4   min_samples_leaf          2          4          6
5       Max_features       sqrt       log2       None
6           accuracy    0.65625   0.633929   0.629464